sonar.host.url=http://host.docker.internal:9000
sonar.token=sqp_bbe23e624f045a3c1329344ec2973d602b89a6b0

sonar.projectKey=hospital
sonar.projectName=hospital
sonar.projectVersion=1.0.0
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

sonar.exclusions=**/*MapperImpl.java
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml