spring.application.name=hospital
# database infos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# File upload size limits for multipart requests
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Secret key for security-related features (JWT, encryption, etc.)
jwt.secret.key=${JWT_SECRET_KEY}
# Duration in seconds
jwt.token.duration=${JWT_TOKEN_DURATION}

# Create a default admin user
app.default.username=${ADMIN_USER}
app.default.password=${ADMIN_PWD}

# Location of files uploaded
file.storage.path=/files

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
spring.web.resources.add-mappings=true